# Generated by Django 3.2.12 on 2023-10-24 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_sec_social_client', models.CharField(max_length=13)),
                ('Type_assurance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_client', models.CharField(max_length=100)),
                ('Prenom_client', models.CharField(max_length=100)),
                ('Age_Client', models.IntegerField()),
                ('Num_sec_social_client', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_fournisseur', models.CharField(max_length=100)),
                ('Adresse_fournisseur', models.CharField(max_length=200)),
                ('Tel_fournisseur', models.IntegerField()),
                ('Mail_fournisseur', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_medic', models.CharField(max_length=100)),
                ('Lot_medic', models.CharField(max_length=20)),
                ('DCI', models.CharField(max_length=100)),
                ('Dosage_medic', models.IntegerField()),
                ('Prix_médic', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Prix_achat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Forme_medic', models.CharField(max_length=20)),
                ('Prémption_medic', models.DateField()),
                ('Quantite_medic', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_vente', models.DateField()),
                ('Quantite_vendue', models.IntegerField()),
                ('ID_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacieapp.client')),
                ('ID_medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacieapp.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_commande', models.DateField()),
                ('Quantite_commande', models.IntegerField()),
                ('ID_medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacieapp.medicament')),
                ('Id_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacieapp.fournisseur')),
            ],
        ),
    ]
